import { MetaMaskContextProvider } from "@/hooks/useMetaMask";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { StoreProvider, store } from "@/store/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <StoreProvider>
        <body className={inter.className}>
          <MetaMaskContextProvider>{children}</MetaMaskContextProvider>
        </body>
      </StoreProvider>
    </html>
  );
}
